apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: app-sre-jenkins
spec:
  metricsEnabled: true
  configurationAsCode:
    configurations:
        - name: app-sre-jcasc
        - name: app-sre-podtemplates
    enabled: true
    defaultConfig: true
    enableAutoReload: true
  roles:
  - name: edit
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
  master:
    containers:
    - name: jenkins
      env:
      - name: OPENSHIFT_ENABLE_OAUTH
        value: 'true'
      - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
        value: 'true'
      - name: DISABLE_ADMINISTRATIVE_MONITORS
        value: 'false'
      - name: KUBERNETES_MASTER
        value: 'https://kubernetes.default:443'
      - name: KUBERNETES_TRUST_CERTIFICATES
        value: 'true'
      - name: JENKINS_UC_INSECURE
        value: 'false'
      - name: JENKINS_HOME
        value: /var/lib/jenkins
      - name: JENKINS_JAVA_OVERRIDES
        value: >-
          -XX:+UnlockExperimentalVMOptions
          -XX:MaxRAMFraction=1
          -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
          -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true
          -Dcasc.reload.token=$(POD_NAME)
      - name: JENKINS_OPTS
        value: >-
          --sessionTimeout=1440
          --sessionEviction=43200
      - name: JENKINS_GC_OPTS
        value: >-
          -XX:+UseParallelGC -XX:MaxPermSize=100m -XX:MinHeapFreeRatio=20
          -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=500m
      - name: INSTALL_PLUGINS
        value: >-       
            ace-editor:1.1,ansicolor:0.7.3,ant:1.10,antisamy-markup-formatter:1.1,apache-httpcomponents-client-4-api:4.5.10-2.0,authentication-tokens:1.3,blueocean:1.23.3,blueocean-autofavorite:1.2.3,blueocean-bitbucket-pipeline:1.23.3,blueocean-commons:1.23.3,blueocean-config:1.23.3,blueocean-core-js:1.23.3,blueocean-dashboard:1.23.3,blueocean-display-url:2.2.0,blueocean-events:1.23.3,blueocean-github-pipeline:1.23.3,blueocean-git-pipeline:1.23.3,blueocean-i18n:1.23.3,blueocean-jira:1.23.3,blueocean-jwt:1.23.3,blueocean-personalization:1.23.3,blueocean-pipeline-api-impl:1.23.3,blueocean-pipeline-editor:1.23.3,blueocean-pipeline-scm-api:1.23.3,blueocean-rest:1.23.3,blueocean-rest-impl:1.23.3,blueocean-web:1.23.3,bootstrap4-api:4.5.3-1,bootstraped-multi-test-results-report:2.1.3,bouncycastle-api:2.17,branch-api:2.6.1,build-timeout:1.20,build-timestamp:1.0.3,checks-api:1.1.0,cloudbees-bitbucket-branch-source:2.4.4,cloudbees-folder:6.14,cobertura:1.16,code-coverage-api:1.2.0,command-launcher:1.2,conditional-buildstep:1.3.1,config-file-provider:3.7.0,configuration-as-code:1.41,credentials:2.3.13,credentials-binding:1.23,display-url-api:2.3.3,docker-commons:1.16,docker-workflow:1.23,durable-task:1.33,echarts-api:4.9.0-2,email-ext:2.79,envinject:2.3.0,envinject-api:1.7,external-monitor-job:1.4,favorite:2.3.1,font-awesome-api:5.15.1-1,ghprb:1.42.1,git:4.4.5,git-client:3.5.1,github:1.31.0,github-api:1.116,github-branch-pr-change-filter:1.2.4,github-branch-source:2.9.1,github-oauth:0.33,github-organization-folder:1.6,github-pullrequest:0.2.8,gitlab-api:1.0.6,git-server:1.7,google-login:1.6,google-oauth-plugin:1.0.0,greenballs:1.15,groovy:2.2,h2-api:1.4.199,handlebars:1.1,handy-uri-templates-2-api:2.1.6-1.0,hashicorp-vault-plugin:2.1.0,htmlpublisher:1.23,icon-shim:2.0.3,jackson2-api:2.11.3,javadoc:1.1,jaxb:2.3.0,jdk-tool:1.0,jenkins-design-language:1.23.3,jenkins-jira-issue-updater:1.18,jira:3.0.17,jira-steps:1.6.0,jira-trigger:1.0.1,jms-messaging:1.1.19,job-dsl:1.77,jquery:1.12.4-1,jquery3-api:3.5.1-2,jquery-detached:1.2.1,jsch:0.1.55.2,junit:1.43,kerberos-sso:1.7,kubernetes:1.25.2,kubernetes-client-api:4.8.0-1,kubernetes-credentials:0.6.2,ldap:1.11,lockable-resources:2.10,mailer:1.32.1,mapdb-api:1.0.9.0,matrix-auth:2.6.2,matrix-project:1.18,maven-plugin:3.8,mercurial:2.3,metrics:4.0.2.5,momentjs:1.1,oauth-credentials:0.3,okhttp-api:3.14.9,openshift-client:1.0.34,openshift-login:1.0.26,openshift-sync:1.0.45,pam-auth:1.6,parameterized-trigger:2.35.2,pipeline-build-step:2.12,pipeline-github-lib:1.0,pipeline-graph-analysis:1.10,pipeline-input-step:2.11,pipeline-maven:3.9.3,pipeline-milestone-step:1.3.1,pipeline-model-api:1.6.0,pipeline-model-declarative-agent:1.1.1,pipeline-model-definition:1.6.0,pipeline-model-extensions:1.6.0,pipeline-rest-api:2.10,pipeline-stage-step:2.3,pipeline-stage-tags-metadata:1.6.0,pipeline-stage-view:2.10,pipeline-utility-steps:2.5.0,plain-credentials:1.7,plugin-util-api:1.4.0,popper-api:1.16.0-7,postbuildscript:2.11.0,prometheus:2.0.0,pubsub-light:1.13,resource-disposer:0.14,role-strategy:3.1,run-condition:0.10,saferestart:0.3,scm-api:2.6.4,script-security:1.75,simple-theme-plugin:0.6,skip-certificate-check:1.0,slack:2.43,snakeyaml-api:1.26.4,sse-gateway:1.21,ssh-agent:1.20,ssh-credentials:1.18.1,ssh-slaves:1.31.2,structs:1.20,subversion:2.13.1,text-finder:1.15,thinBackup:1.10,throttle-concurrents:2.0.3,timestamper:1.11.3,token-macro:2.12,trilead-api:1.0.12,variant:1.3,view-job-filters:2.3,windows-slaves:1.0,workflow-aggregator:2.6,workflow-api:2.40,workflow-basic-steps:2.18,workflow-cps:2.84,workflow-cps-global-lib:2.15,workflow-durable-task-step:2.31,workflow-job:2.40,workflow-multibranch:2.20,workflow-remote-loader:1.5,workflow-scm-step:2.11,workflow-step-api:2.23,workflow-support:3.5,ws-cleanup:0.38
      image: 'quay.io/openshift/origin-jenkins:4.7'
      livenessProbe:
        failureThreshold: 2
        httpGet:
          path: /login
          port: 8080
        initialDelaySeconds: 420
        periodSeconds: 360
        timeoutSeconds: 300
      readinessProbe:
        httpGet:
          path: /login
          port: 8080
        initialDelaySeconds: 3
        timeoutSeconds: 240
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins-operator"}}'